/* 
------------------------------CREATE VIEW VW_VENDAS_POR_PRODUTO_ANUALMENTE------------------------------
AUTOR: WILLIAM SAMPAIO RAMOS
DATA: 23/08/2022
DESCRIÇÃO: CRIAÇÃO DE VIEW PARA FILTRAR O TOTAL DE VENDAS ANUAIS DOS PRODUTOS
------------------------------------------------------------------------------------------------------
*/

CREATE OR REPLACE VIEW VW_VENDAS_POR_PRODUTO_ANUALMENTE
AS
SELECT 
      DECODE(INF.CODIGO_DO_PRODUTO, 
        INF.CODIGO_DO_PRODUTO, (SELECT TP.NOME_DO_PRODUTO FROM  TABELA_DE_PRODUTOS TP  WHERE TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO)
        ) AS NOME_DO_PRODUTO
        ,SUM(INF.QUANTIDADE) AS TOTAL_VENDAS
        ,TO_CHAR(NF.DATA_VENDA, 'YYYY') AS MES_ANO
FROM itens_notas_fiscais INF
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
GROUP BY INF.CODIGO_DO_PRODUTO, TO_CHAR(NF.DATA_VENDA, 'YYYY') --HAVING SUM(ITF.QUANTIDADE) > 394000
ORDER BY TO_CHAR(NF.DATA_VENDA, 'YYYY');

COMMIT;

/