/* 
------------------------------CREATE VIEW VW_FATURAMENTO_CLIENTE-------------------------------------------
AUTOR: WILLIAM SAMPAIO RAMOS
DATA: 23/08/2022
DESCRIÇÃO: CRIAÇÃO DE VIEW PARA VERIFICAR O FATURAMENTO TOTAL POR CLIENTE ANUALMENTE
------------------------------------------------------------------------------------------------------
*/

CREATE OR REPLACE VIEW VW_FATURAMENTO_CLIENTE_ANUAL
AS
SELECT
    CONCAT(CONCAT(CONCAT(CONCAT(CONCAT('O CLIENTE ', UPPER(TC.NOME)), ' FATUROU '), 
    FLOOR(SUM(INF.QUANTIDADE * INF.PRECO))), ' NO ANO DE '),
    EXTRACT(YEAR FROM DATA_VENDA)) AS FATURAMENTO
FROM
    TABELA_DE_CLIENTES TC
INNER JOIN NOTAS_FISCAIS NF ON TC.CPF = NF.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
GROUP BY TC.NOME, EXTRACT(YEAR FROM DATA_VENDA)
ORDER BY TC.NOME, EXTRACT(YEAR FROM DATA_VENDA);

COMMIT;

/