/* 
------------------------------CREATE VIEW VW_VENDAS_POR_SABOR_ANUALMENTE------------------------------
AUTOR: WILLIAM SAMPAIO RAMOS
DATA: 23/08/2022
DESCRIÇÃO: CRIAÇÃO DE VIEW PARA FILTRAR O TOTAL DE VENDAS ANUAIS DOS PRODUTOS POR SABOR
------------------------------------------------------------------------------------------------------
*/

CREATE OR REPLACE VIEW VW_VENDAS_POR_SABOR_ANUALMENTE
AS
SELECT
    TP.SABOR
    ,SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL
    ,EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO
FROM ITENS_NOTAS_FISCAIS INF
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_PRODUTOS TP ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
GROUP BY TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA) --HAVING SUM(ITF.QUANTIDADE) > 394000
ORDER BY TP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA), SUM(INF.QUANTIDADE) DESC;

COMMIT;

/